version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: device-test-node
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"

    volumes:
      - ./sql:/docker-entrypoint-initdb.d